/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.view;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.Article;
import hr.algebra.model.Person;
import hr.algebra.utilities.FileUtils;
import hr.algebra.utilities.IconUtils;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.model.ArticleTableModel;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author filip
 */
public class EditArticlesPanel extends javax.swing.JPanel {

    /**
     * Creates new form UploadArticlesPanel
     */
    public EditArticlesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbArticles = new javax.swing.JTable();
        lbIcon = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();
        tfPicturePath = new javax.swing.JTextField();
        lbPicturePathError = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        lbTitleError = new javax.swing.JLabel();
        lbLinkError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfLink = new javax.swing.JTextField();
        lbDateError = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPublishDate = new javax.swing.JTextField();
        lbCreatorError = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfCreator = new javax.swing.JTextField();
        lbContributorsError = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfContributors = new javax.swing.JTextField();
        lbDescriptionError = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        taDescription = new javax.swing.JTextField();
        taContent = new javax.swing.JTextField();
        lbContentError = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tbArticles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbArticles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbArticlesMouseClicked(evt);
            }
        });
        tbArticles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbArticlesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbArticles);

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no_image.png"))); // NOI18N

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        tfPicturePath.setEditable(false);

        lbPicturePathError.setForeground(new java.awt.Color(255, 0, 51));
        lbPicturePathError.setText("X");

        jLabel3.setText("Title");

        lbTitleError.setForeground(new java.awt.Color(255, 0, 0));
        lbTitleError.setText("X");

        lbLinkError.setForeground(new java.awt.Color(255, 0, 0));
        lbLinkError.setText("X");

        jLabel6.setText("Link");

        lbDateError.setForeground(new java.awt.Color(255, 0, 0));
        lbDateError.setText("X");

        jLabel8.setText("Publish date");

        tfPublishDate.setName("DATE"); // NOI18N

        lbCreatorError.setForeground(new java.awt.Color(255, 0, 0));
        lbCreatorError.setText("X");

        jLabel10.setText("Creator");

        lbContributorsError.setForeground(new java.awt.Color(255, 0, 0));
        lbContributorsError.setText("X");

        jLabel12.setText("Contributors");

        lbDescriptionError.setForeground(new java.awt.Color(255, 0, 0));
        lbDescriptionError.setText("X");

        jLabel14.setText("Description");

        lbContentError.setForeground(new java.awt.Color(255, 0, 0));
        lbContentError.setText("X");

        jLabel18.setText("Content");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbTitleError))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(455, 455, 455))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbLinkError)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(455, 455, 455))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(tfPublishDate, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbDateError)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(455, 455, 455))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(tfCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbCreatorError)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(455, 455, 455))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(tfContributors, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbContributorsError)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taDescription)
                                .addGap(18, 18, 18)
                                .addComponent(lbDescriptionError)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taContent, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbContentError)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnAdd)
                                        .addGap(62, 62, 62)
                                        .addComponent(btnUpdate)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnDelete))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 636, Short.MAX_VALUE)
                                .addComponent(lbPicturePathError)
                                .addGap(18, 18, 18)
                                .addComponent(tfPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnChoose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTitleError))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbLinkError))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfPublishDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbDateError))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfCreator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbCreatorError))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfContributors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbContributorsError))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbDescriptionError)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(taDescription)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnChoose)
                                    .addComponent(tfPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPicturePathError)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdd)
                                .addComponent(btnUpdate))
                            .addComponent(btnDelete))
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbContentError)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(taContent))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!formValid()) {
            return;
        }

        try {
            String localPath = uploadPicture();

            /*Creator check*/
            Person creator = new Person();
            String fullName = tfCreator.getText().trim();
            String[] nameParts = fullName.split(" ");

            if (nameParts.length >= 2) {
                String inputName = nameParts[0];
                String inputSurname = nameParts[1];

                List<Person> people = repository.selectPeople();

                for (Person person : people) {
                    if (person.getName().equalsIgnoreCase(inputName)
                            && person.getSurname().equalsIgnoreCase(inputSurname)) {

                        creator = person;
                    } else {
                        Person newPerson = new Person(inputName, inputSurname);
                        int idPerson = repository.createPerson(newPerson);
                        newPerson.setId(idPerson);
                        creator = newPerson;
                    }
                }
            }

            Article article = new Article(
                    tfTitle.getText().trim(),
                    tfLink.getText().trim(),
                    taDescription.getText().trim(),
                    LocalDateTime.parse(
                            tfPublishDate.getText().trim(),
                            Article.DATE_FORMATTER
                    ),
                    creator,
                    localPath,
                    taContent.getText().trim()
            );
            
            int idA = repository.createArticle(article);
            article.setId(idA);
            /*Contributor check*/
            String contributorsText = tfContributors.getText().trim();
            List<Person> existingContributors = new ArrayList<>();
            List<Person> newContributors = new ArrayList<>();
            List<Integer> contributorIds = new ArrayList<>();

            if (!contributorsText.isEmpty()) {
                String[] names = contributorsText.split(", ");

                List<Person> peopleInDb = repository.selectPeople();

                for (String full_Name : names) {
                    String[] parts = full_Name.trim().split(" ");
                    if (parts.length >= 2) {
                        String name = parts[0];
                        String surname = parts[1];

                        Optional<Person> match = peopleInDb.stream()
                                .filter(p -> p.getName().equalsIgnoreCase(name)
                                && p.getSurname().equalsIgnoreCase(surname))
                                .findFirst();

                        if (match.isPresent()) {
                            existingContributors.add(match.get());
                        } else {
                            newContributors.add(new Person(name, surname));
                        }
                    } else {
                        System.err.println("Invalid contributor name: " + full_Name);
                    }
                }

                List<Integer> newContributorIds = repository.createPeople(newContributors);

                contributorIds.addAll(
                        existingContributors.stream()
                                .map(Person::getId)
                                .collect(Collectors.toList())
                );
                contributorIds.addAll(newContributorIds);
                repository.insertArticleContributor(article.getId(), contributorIds);
            }

            List<Person> finalContributors = new ArrayList<>();

            for (Integer id : contributorIds) {
                repository.selectPerson(id).ifPresent(finalContributors::add);
            }

            article.setContributors(finalContributors);
            model.setArticles(repository.selectArticles());
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        Optional<File> optionalFile = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");

        if (optionalFile.isEmpty()) {
            return;
        }

        File file = optionalFile.get();
        tfPicturePath.setText(file.getAbsolutePath());
        setIcon(lbIcon, file);
    }//GEN-LAST:event_btnChooseActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown

    private void tbArticlesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbArticlesKeyReleased
        selectArticle();
    }//GEN-LAST:event_tbArticlesKeyReleased

    private void tbArticlesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbArticlesMouseClicked
        selectArticle();
    }//GEN-LAST:event_tbArticlesMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedArticle == null) {
            MessageUtils.showInformationMessage("INFO", "Please select an Article!");
            return;
        }

        if (!formValid()) {
            return;
        }

        try {

            if (!tfPicturePath.getText().trim().equals(selectedArticle.getPicturePath())) {
                if (Files.exists(Paths.get(selectedArticle.getPicturePath()))) {
                    Files.deleteIfExists(Paths.get(selectedArticle.getPicturePath()));
                }
                String localPath = uploadPicture();
                selectedArticle.setPicturePath(localPath);
            }

            selectedArticle.setTitle(tfTitle.getText().trim());
            selectedArticle.setLink(tfLink.getText().trim());
            selectedArticle.setDescription(taDescription.getText().trim());
            selectedArticle.setPublishedDate(LocalDateTime.parse(
                    tfPublishDate.getText().trim(),
                    Article.DATE_FORMATTER
            ));
            selectedArticle.setContent(taContent.getText().trim());

            /*Creator check*/
            String fullName = tfCreator.getText().trim();
            String[] nameParts = fullName.split(" ");

            if (nameParts.length >= 2) {
                String inputName = nameParts[0];
                String inputSurname = nameParts[1];

                List<Person> people = repository.selectPeople();

                for (Person person : people) {
                    if (person.getName().equalsIgnoreCase(inputName)
                            && person.getSurname().equalsIgnoreCase(inputSurname)) {

                        selectedArticle.setCreator(person);
                    } else {
                        Person newPerson = new Person(inputName, inputSurname);
                        int idPerson = repository.createPerson(newPerson);
                        newPerson.setId(idPerson);
                        selectedArticle.setCreator(newPerson);
                    }
                }
            }

            /*Contributor check*/
            String contributorsText = tfContributors.getText().trim();
            List<Person> existingContributors = new ArrayList<>();
            List<Person> newContributors = new ArrayList<>();
            List<Integer> contributorIds = new ArrayList<>();

            if (!contributorsText.isEmpty()) {
                String[] names = contributorsText.split(", ");

                List<Person> peopleInDb = repository.selectPeople();

                for (String full_Name : names) {
                    String[] parts = full_Name.trim().split(" ");
                    if (parts.length >= 2) {
                        String name = parts[0];
                        String surname = parts[1];

                        Optional<Person> match = peopleInDb.stream()
                                .filter(p -> p.getName().equalsIgnoreCase(name)
                                && p.getSurname().equalsIgnoreCase(surname))
                                .findFirst();

                        if (match.isPresent()) {
                            existingContributors.add(match.get());
                        } else {
                            newContributors.add(new Person(name, surname));
                        }
                    } else {
                        System.err.println("Invalid contributor name: " + full_Name);
                    }
                }

                List<Integer> newContributorIds = repository.createPeople(newContributors);

                contributorIds.addAll(
                        existingContributors.stream()
                                .map(Person::getId)
                                .collect(Collectors.toList())
                );
                contributorIds.addAll(newContributorIds);
                repository.insertArticleContributor(selectedArticle.getId(), contributorIds);
            }

            List<Person> finalContributors = new ArrayList<>();

            for (Integer id : contributorIds) {
                repository.selectPerson(id).ifPresent(finalContributors::add);
            }

            selectedArticle.setContributors(finalContributors);
            repository.updateArticle(selectedArticle.getId(), selectedArticle);
            model.setArticles(repository.selectArticles());
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedArticle == null) {
            MessageUtils.showInformationMessage("INFO", "Please select an Article!");
            return;
        }

        try {

            if (Files.exists(Paths.get(selectedArticle.getPicturePath()))) {
                Files.deleteIfExists(Paths.get(selectedArticle.getPicturePath()));
            }

            List<Person> cont = repository.getArticleContributors(selectedArticle.getId());

            List<Integer> cont_Ids = cont.stream()
                    .map(Person::getId)
                    .collect(Collectors.toList());

            repository.deleteArticleContributor(selectedArticle.getId(), cont_Ids);
            repository.deleteArticle(selectedArticle.getId());
            model.setArticles(repository.selectArticles());
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void setIcon(JLabel label, File file) {
        try {
            label.setIcon(IconUtils.createIcon(file, label.getWidth(), label.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(EditArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to set icon!");
        }
    }

    private List<JTextComponent> validationFields;
    private List<JLabel> errorLabels;

    private Repository repository;
    private ArticleTableModel model;

    private Article selectedArticle;

    private void init() {
        try {
            initValidation();
            hideErrors();
            initRepository();
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(EditArticlesPanel.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

    private void initRepository() throws Exception {
        repository = RepositoryFactory.getRepository();
    }

    private void initTable() throws Exception {
        tbArticles.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbArticles.setAutoCreateRowSorter(true);
        tbArticles.setRowHeight(25);
        model = new ArticleTableModel(repository.selectArticles());
        tbArticles.setModel(model);
    }

    private void initValidation() {
        validationFields = Arrays.asList(
                tfTitle,
                tfLink,
                tfPublishDate,
                tfCreator,
                tfContributors,
                taDescription,
                taContent,
                tfPicturePath
        );
        errorLabels = Arrays.asList(
                lbTitleError,
                lbLinkError,
                lbDateError,
                lbCreatorError,
                lbContributorsError,
                lbDescriptionError,
                lbContentError,
                lbPicturePathError
        );
    }

    private void hideErrors() {
        errorLabels.forEach(e -> e.setVisible(false));
    }

    private boolean formValid() {
        hideErrors();
        boolean ok = true;

        for (int i = 0; i < validationFields.size(); i++) {
            ok &= !validationFields.get(i).getText().trim().isEmpty();
            errorLabels.get(i).setVisible(validationFields.get(i).getText().trim().isEmpty());

            if ("DATE".equals(validationFields.get(i).getName())) {
                try {
                    LocalDateTime.parse(
                            validationFields.get(i).getText().trim(),
                            Article.DATE_FORMATTER
                    );
                } catch (Exception e) {
                    ok = false;
                    errorLabels.get(i).setVisible(true);
                }
            }
        }
        return ok;
    }

    private void clearForm() {
        hideErrors();
        validationFields.forEach(e -> e.setText(""));
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no_image.png")));
        selectedArticle = null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbContentError;
    private javax.swing.JLabel lbContributorsError;
    private javax.swing.JLabel lbCreatorError;
    private javax.swing.JLabel lbDateError;
    private javax.swing.JLabel lbDescriptionError;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbLinkError;
    private javax.swing.JLabel lbPicturePathError;
    private javax.swing.JLabel lbTitleError;
    private javax.swing.JTextField taContent;
    private javax.swing.JTextField taDescription;
    private javax.swing.JTable tbArticles;
    private javax.swing.JTextField tfContributors;
    private javax.swing.JTextField tfCreator;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfPicturePath;
    private javax.swing.JTextField tfPublishDate;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables

    private String uploadPicture() throws IOException {
        String source = tfPicturePath.getText();
        String ext = source.substring(source.lastIndexOf("."));
        String name = UUID.randomUUID().toString() + ext;

        String destination = DIR + File.separator + name;

        FileUtils.copy(source, destination);

        return destination;
    }
    private static final String DIR = "assets";

    private void selectArticle() {
        int selectedRow = tbArticles.getSelectedRow();
        int rowIndex = tbArticles.convertRowIndexToModel(selectedRow);

        int id = (int) model.getValueAt(rowIndex, 0);

        try {
            Optional<Article> opt = repository.selectArticle(id);
            if (opt.isPresent()) {
                selectedArticle = opt.get();
                fillForm(selectedArticle);
            }
        } catch (Exception exception) {
        }
    }

    private void fillForm(Article article) {
        tfTitle.setText(article.getTitle());
        tfLink.setText(article.getLink());
        tfPublishDate.setText(article.getPublishedDate().format(Article.DATE_FORMATTER));
        tfCreator.setText(article.getCreator().toString());

        List<Person> contributors = article.getContributors();
        String contributorsStr = contributors.stream()
                .map(p -> p.getName() + " " + p.getSurname())
                .collect(Collectors.joining(", "));

        tfContributors.setText(contributorsStr);
        taDescription.setText(article.getDescription());
        taContent.setText(article.getContent());
        tfPicturePath.setText(article.getPicturePath());

        setIcon(lbIcon, new File(article.getPicturePath()));
    }
}
